SIGESF/Controllers/AgenteSupridoController.cs
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SIGESF.Models;
using PagedList;
using System;

namespace SIGESF.Controllers
{
    public class AgenteSupridoController : Controller
    {
        private ContextoEF db = new ContextoEF();

        // GET: AgenteSuprido
        public ViewResult Index(string sortOrder, string currenteFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NomeParam = String.IsNullOrEmpty(sortOrder) ? "Nome_desc" : "";
            ViewBag.MatriculaParam = sortOrder == "Matricula" ? "Matricula_desc" : "Matricula";
            ViewBag.UnidadeParam = sortOrder == "Unidade" ? "Unidade_desc" : "Unidade";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currenteFilter;
            }

            ViewBag.CurrenteFilter = searchString;

            var supridos = from s in db.AgentesSupridos
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                supridos = supridos.Where(s => s.Nome.ToUpper().Contains(searchString.ToUpper())
                                            || s.Unidades.ToString().Contains(searchString)
                                            || s.Matricula.ToString().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "Nome_desc":
                    supridos = supridos.OrderByDescending(s => s.Nome);
                    break;
                case "Matricula":
                    supridos = supridos.OrderBy(s => s.Matricula);
                    break;
                case "Matricula_desc":
                    supridos = supridos.OrderByDescending(s => s.Matricula);
                    break;
                case "Unidade":
                    supridos = supridos.OrderBy(s => s.Unidades);
                    break;
                case "Unidade_desc":
                    supridos = supridos.OrderByDescending(s => s.Unidades);
                    break;
                default:
                    supridos = supridos.OrderBy(s => s.Nome);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(supridos.ToPagedList(pageNumber, pageSize));
        }


        // GET: AgenteSuprido/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgenteSuprido agenteSuprido = db.AgentesSupridos.Find(id);
            if (agenteSuprido == null)
            {
                return HttpNotFound();
            }
            return View(agenteSuprido);
        }

        // GET: AgenteSuprido/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AgenteSuprido/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AgenteSupridoId,Nome,Matricula,CPF,Unidades")] AgenteSuprido agenteSuprido)
        {
            if (ModelState.IsValid)
            {
                db.AgentesSupridos.Add(agenteSuprido);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(agenteSuprido);
        }

        // GET: AgenteSuprido/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgenteSuprido agenteSuprido = db.AgentesSupridos.Find(id);
            if (agenteSuprido == null)
            {
                return HttpNotFound();
            }
            return View(agenteSuprido);
        }

        // POST: AgenteSuprido/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AgenteSupridoId,Nome,Matricula,CPF,Unidades")] AgenteSuprido agenteSuprido)
        {
            if (ModelState.IsValid)
            {
                db.Entry(agenteSuprido).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(agenteSuprido);
        }

        // GET: AgenteSuprido/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AgenteSuprido agenteSuprido = db.AgentesSupridos.Find(id);
            if (agenteSuprido == null)
            {
                return HttpNotFound();
            }
            return View(agenteSuprido);
        }

        // POST: AgenteSuprido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AgenteSuprido agenteSuprido = db.AgentesSupridos.Find(id);
            db.AgentesSupridos.Remove(agenteSuprido);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SIGESF/Controllers/NaturezaDespesaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SIGESF.Models;

namespace SIGESF.Controllers
{
    public class NaturezaDespesaController : Controller
    {
        private ContextoEF db = new ContextoEF();

        // GET: NaturezaDespesa
        public ActionResult Index()
        {
            return View(db.NaturezasDespesas.ToList());
        }

        // GET: NaturezaDespesa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NaturezaDespesa naturezaDespesa = db.NaturezasDespesas.Find(id);
            if (naturezaDespesa == null)
            {
                return HttpNotFound();
            }
            return View(naturezaDespesa);
        }

        // GET: NaturezaDespesa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NaturezaDespesa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NaturezaDespesaId,CodigoDespesa,Descricao")] NaturezaDespesa naturezaDespesa)
        {
            if (ModelState.IsValid)
            {
                db.NaturezasDespesas.Add(naturezaDespesa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(naturezaDespesa);
        }

        // GET: NaturezaDespesa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NaturezaDespesa naturezaDespesa = db.NaturezasDespesas.Find(id);
            if (naturezaDespesa == null)
            {
                return HttpNotFound();
            }
            return View(naturezaDespesa);
        }

        // POST: NaturezaDespesa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NaturezaDespesaId,CodigoDespesa,Descricao")] NaturezaDespesa naturezaDespesa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(naturezaDespesa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(naturezaDespesa);
        }

        // GET: NaturezaDespesa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NaturezaDespesa naturezaDespesa = db.NaturezasDespesas.Find(id);
            if (naturezaDespesa == null)
            {
                return HttpNotFound();
            }
            return View(naturezaDespesa);
        }

        // POST: NaturezaDespesa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NaturezaDespesa naturezaDespesa = db.NaturezasDespesas.Find(id);
            db.NaturezasDespesas.Remove(naturezaDespesa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SIGESF/Areas/Administracao/Views/Shared/BreadcrumbsPartial.cshtml
<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
           try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
    </script>

    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="@Url.Action("Index", "Dashboard")">Home</a>
        </li>

        @if (@Html.Action() == "Index")
        {
            <li class="active">
                <a href="@Url.Action("Index", @Html.Controller())">@Html.Controller()</a>
            </li>
        }
        else
        {
            <li>
                <a href="@Url.Action("Index", @Html.Controller())">@Html.Controller()</a>
            </li>
            <li class="active">@Html.Action()</li>
        }
    </ul><!-- /.breadcrumb -->

    @*<div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="ace-icon fa fa-search nav-search-icon"></i>
            </span>
        </form>
    </div>*@<!-- /.nav-search -->
</div>

SIGESF/Areas/Administracao/Views/Shared/FooterPartial.cshtml
@*<div class="footer">
    <div class="footer-inner">
        
    </div>
</div>*@

SIGESF/Areas/Administracao/Views/Shared/NavigatorBarList - Cópia .cshtml
<ul class="nav nav-list">
    <li class="">
        <a href="@Url.Action("Index", "Dashboard")">
            <i class="menu-icon fa fa-tachometer"></i>
            <span class="menu-text"> Dashboard </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-desktop"></i>
            <span class="menu-text">
                UI &amp; Elements
            </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-caret-right"></i>

                    Layouts
                    <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                    <li class="">
                        <a href="@Url.Action("TopMenu", "UIElements")">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Top Menu
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="">
                        <a href="@Url.Action("TwoMenu1", "UIElements")">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Two Menus 1
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="">
                        <a href="@Url.Action("TwoMenu2", "UIElements")">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Two Menus 2
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="">
                        <a href="@Url.Action("MobileMenu1", "UIElements")">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Default Mobile Menu
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="">
                        <a href="@Url.Action("MobileMenu2", "UIElements")">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Mobile Menu 2
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="">
                        <a href="@Url.Action("MobileMenu3", "UIElements")">
                            <i class="menu-icon fa fa-caret-right"></i>
                            Mobile Menu 3
                        </a>

                        <b class="arrow"></b>
                    </li>
                </ul>
            </li>

            <li class="">
                <a href="@Url.Action("Typography", "UIElements")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Typography
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Elements", "UIElements")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Elements
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Buttons", "UIElements")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Buttons &amp; Icons
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("ContentSliders", "UIElements")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Content Sliders
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("TreeView", "UIElements")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Treeview
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("JQueryUI", "UIElements")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    jQuery UI
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("NestableLists", "UIElements")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Nestable Lists
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="#" class="dropdown-toggle">
                    <i class="menu-icon fa fa-caret-right"></i>

                    Three Level Menu
                    <b class="arrow fa fa-angle-down"></b>
                </a>

                <b class="arrow"></b>

                <ul class="submenu">
                    <li class="">
                        <a href="#">
                            <i class="menu-icon fa fa-leaf green"></i>
                            Item #1
                        </a>

                        <b class="arrow"></b>
                    </li>

                    <li class="">
                        <a href="#" class="dropdown-toggle">
                            <i class="menu-icon fa fa-pencil orange"></i>

                            4th level
                            <b class="arrow fa fa-angle-down"></b>
                        </a>

                        <b class="arrow"></b>

                        <ul class="submenu">
                            <li class="">
                                <a href="#">
                                    <i class="menu-icon fa fa-plus purple"></i>
                                    Add Product
                                </a>

                                <b class="arrow"></b>
                            </li>

                            <li class="">
                                <a href="#">
                                    <i class="menu-icon fa fa-eye pink"></i>
                                    View Products
                                </a>

                                <b class="arrow"></b>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Tables </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("Table", "Tables")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Simple &amp; Dynamic
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("JQGrid", "Tables")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    jqGrid plugin
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-pencil-square-o"></i>
            <span class="menu-text"> Forms </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("FormElements", "Forms")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Form Elements
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("FormElements2", "Forms")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Form Elements 2
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("FormWizard", "Forms")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Wizard &amp; Validation
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("WYSIWYG", "Forms")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Wysiwyg &amp; Markdown
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Dropzone", "Forms")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Dropzone File Upload
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="@Url.Action("Index", "Widgets")">
            <i class="menu-icon fa fa-list-alt"></i>
            <span class="menu-text"> Widgets </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="@Url.Action("Index", "Calendar")">
            <i class="menu-icon fa fa-calendar"></i>

            <span class="menu-text">
                Calendar

                <span class="badge badge-transparent tooltip-error" title="2 Important Events">
                    <i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>
                </span>
            </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="@Url.Action("Index", "Gallery")">
            <i class="menu-icon fa fa-picture-o"></i>
            <span class="menu-text"> Gallery </span>
        </a>

        <b class="arrow"></b>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-tag"></i>
            <span class="menu-text"> More Pages </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("ProfilePage", "MorePages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    User Profile
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Inbox", "MorePages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Inbox
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Pricing", "MorePages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Pricing Tables
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Invoice", "MorePages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Invoice
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Timeline", "MorePages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Timeline
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("EmailTemplates", "MorePages" )">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Email Templates
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Login", "MorePages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Login &amp; Register
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>

    <li class="active open">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-file-o"></i>

            <span class="menu-text">
                Other Pages

                <span class="badge badge-primary">5</span>
            </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("FAQ", "OtherPages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    FAQ
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Error404", "OtherPages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Error 404
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Error500", "OtherPages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Error 500
                </a>

                <b class="arrow"></b>
            </li>

            <li class="">
                <a href="@Url.Action("Grid", "OtherPages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Grid
                </a>

                <b class="arrow"></b>
            </li>

            <li class="active">
                <a href="@Url.Action("Blank", "OtherPages")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    Blank Page
                </a>

                <b class="arrow"></b>
            </li>
        </ul>
    </li>
</ul><!-- /.nav-list -->

SIGESF/Areas/Administracao/Views/Shared/NavigatorBarList.cshtml
<ul class="nav nav-list">
    
    @*@if (User.IsInRole("Administrador"))
    {*@
    <li class="">
        <a href="@Url.Action("Index", "Home")">
            <i class="menu-icon fa fa-home"></i>
            <span class="menu-text"> Home </span>
        </a>
    </li>
    

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-list"></i>
            <span class="menu-text"> Agentes Supridos </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("Create","AgenteSuprido")">
                    <i class="menu-icon fa fa-group"></i>
                    <span class="menu-text"> Cadastrar novo </span>
                </a>
            </li>
            <li class="">
                <a href="@Url.Action("Index","AgenteSuprido")">
                    <i class="menu-icon fa fa-group"></i>
                    <span class="menu-text"> Manter Agentes Supridos </span>
                </a>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-shopping-cart"></i>
            <span class="menu-text"> Solicitações SF </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("Create","SolicitacaoSuprimentoFundos")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Incluir Solicitação </span>
                </a>
            </li>
            <li class="">
                <a href="@Url.Action("Index","SolicitacaoSuprimentoFundos")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Manter Solicitação </span>
                </a>
            </li>
            <li class="">
                <a href="@Url.Action("Create","DetalheSolicitacaoSuprimentoFundos")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Incluir Detalhes Solicitação </span>
                </a>
            </li>
            <li class="">
                <a href="@Url.Action("Index","DetalheSolicitacaoSuprimentoFundos")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Manter Detalhes Solicitação </span>
                </a>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-money"></i>
            <span class="menu-text"> Concessões SF </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("Create","ConcessaoSuprimentoFundos")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Incluir nova Concessão </span>
                </a>
            </li>

            <li class="">
                <a href="@Url.Action("Index","ConcessaoSuprimentoFundos")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Manter Dados de Concessão </span>
                </a>
            </li>
            <li class="">
                <a href="@Url.Action("Create","DetalheConcessaoAplicacaoSF")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Incluir Detalhes Concessão </span>
                </a>
            </li>

            <li class="">
                <a href="@Url.Action("Index","DetalheConcessaoAplicacaoSF")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Manter Detalhes de Concessão </span>
                </a>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-dollar"></i>
            <span class="menu-text"> Grupo Despesa </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("Create","NaturezaDespesa")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Cadastro Nat Despesa </span>
                </a>
            </li>

            <li class="">
                <a href="@Url.Action("Index","NaturezaDespesa")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Manter Cadastro Despesa </span>
                </a>
            </li>
        </ul>
    </li>

    <li class="">
        <a href="#" class="dropdown-toggle">
            <i class="menu-icon fa fa-print"></i>
            <span class="menu-text"> Relatórios </span>

            <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
            <li class="">
                <a href="@Url.Action("RelatorioGeralAgentesSupridos","Relatorio")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Agentes Supridos </span>
                </a>
            </li>

            <li class="">
                <a href="@Url.Action("RelatorioGeralSolicitacoes","Relatorio")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Solicitações SF </span>
                </a>
            </li>

            <li class="">
                <a href="@Url.Action("RelatorioGeralConcessao","Relatorio")">
                    <i class="menu-icon fa fa-caret-right"></i>
                    <span class="menu-text"> Concessões SF </span>
                </a>
            </li>
    </li>
    @*}*@
</ul><!-- /.nav-list -->